# Deployment do Postgres
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgre
spec:
  selector:
    matchLabels:
      app: postgre
  template:
    metadata:
      labels:
        app: postgre 
    spec:
      containers:
        - name: postgre
          image: postgres:14;3
          ports: 
            - containerPort: 5432
          env:
         - name: POSTGRES_PASSWORD
           value: "kubedevnews"
           
  